#!/usr/bin/env python3
"""
apparmor_manager.py — Generate, load, and remove the AppArmor execution jail.

The profile confines bash and zsh so they can only exec Firefox and its helpers.
All other exec attempts are denied.
"""

import subprocess
import logging
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

PROFILE_NAME = "qudurat-exec-jail"
PROFILES_DIR = Path("/opt/qudurat-jail/profiles")
PROFILE_PATH = PROFILES_DIR / PROFILE_NAME


def generate_profile(config: dict[str, Any]) -> str:
    extra_allowed: list[str] = config.get("execution", {}).get("extra_allowed", [])

    extra_rules = ""
    for binary in extra_allowed:
        extra_rules += f"  {binary} ix,\n"

    profile = f"""# qudurat-exec-jail — auto-generated by qudurat_kernel_jail
# Confines bash/zsh to only execute Firefox.

profile {PROFILE_NAME} /usr/bin/{{ba,z}}sh {{
  # Shell self-read
  /usr/bin/{{ba,z}}sh mr,

  # Dynamic linker and libraries
  /etc/ld.so.cache r,
  /usr/lib/** mr,
  /usr/lib64/** mr,

  # Proc/sys reads shells may need
  /proc/*/status r,
  /proc/*/fd/ r,
  /proc/meminfo r,

  # Firefox binary and all its helpers / resources
  /usr/bin/firefox ix,
  /usr/lib/firefox/ r,
  /usr/lib/firefox/** ix,

  # Extra allowed binaries (from config)
{extra_rules}
  # Deny execution of everything else
  deny /usr/bin/* x,
  deny /usr/local/bin/* x,
  deny /bin/* x,
  deny /sbin/* x,
  deny /usr/sbin/* x,
  deny /usr/local/sbin/* x,
  deny /opt/** x,
  deny /snap/** x,
  deny /home/** x,
  deny /root/** x,
  deny /tmp/** x,
}}
"""
    return profile


def write_profile(config: dict[str, Any]) -> None:
    PROFILES_DIR.mkdir(parents=True, exist_ok=True)
    content = generate_profile(config)
    PROFILE_PATH.write_text(content)
    log.info("Wrote AppArmor profile to %s", PROFILE_PATH)


def load_profile() -> None:
    """Parse and load the profile into the kernel."""
    subprocess.run(["apparmor_parser", "-r", str(PROFILE_PATH)], check=True)
    log.info("Loaded AppArmor profile %s", PROFILE_NAME)


def enforce_profile() -> None:
    """Set the profile to enforcing mode."""
    subprocess.run(["aa-enforce", str(PROFILE_PATH)], check=True)
    log.info("AppArmor profile %s set to enforce mode", PROFILE_NAME)


def disable_profile() -> None:
    """Remove the profile from the kernel."""
    result = subprocess.run(
        ["aa-disable", str(PROFILE_PATH)],
        capture_output=True,
    )
    if result.returncode != 0:
        log.warning(
            "aa-disable returned %d: %s",
            result.returncode,
            result.stderr.decode().strip(),
        )
    else:
        log.info("AppArmor profile %s disabled", PROFILE_NAME)


def apparmor_available() -> bool:
    result = subprocess.run(
        ["aa-status", "--enabled"],
        capture_output=True,
    )
    return result.returncode == 0


def apply(config: dict[str, Any]) -> None:
    if not apparmor_available():
        log.warning(
            "AppArmor is not enabled in the kernel. "
            "Run install.sh and reboot to activate execution restrictions."
        )
        return
    write_profile(config)
    load_profile()
    enforce_profile()


def remove() -> None:
    if not apparmor_available():
        log.info("AppArmor not active — nothing to disable")
        return
    disable_profile()
